/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoseguridad;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultListModel;

/**
 *
 * @author rafaelpelacchi
 */
public class AdministracionMenu extends javax.swing.JFrame {

    /**
     * Creates new form FinalMenu
     */
    
    ArrayList<Usuario> misusuarios = new ArrayList<Usuario>();
    Usuario seleccionado;
    public AdministracionMenu() {
        initComponents();
        cargarPagina();
    }
    
    public void cargarPagina(){ 
        this.listUsuarios.clearSelection();
        cargarUsuarios();
        seleccionado = null;
        this.btnCancelar.setVisible(false);
        this.btnEditar.setText("Editar"); 
        habilitacionTextos(false);
        this.lblError.setVisible(false);
    }
    
    public void habilitacionTextos(boolean valor){
        this.txtNombre.setEnabled(valor);
        this.txtApellido.setEnabled(valor);
        this.txtPassword.setEnabled(valor);
        this.txtCedula.setEnabled(valor);
    }
    
    public void cargarUsuarios(){
        ABM.llenarTablaInicialUsuarios(misusuarios);
        DefaultListModel md = new DefaultListModel();
        for(Usuario x: misusuarios){
            md.addElement(x);
        }
        this.listUsuarios.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Menu de Adminitracion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        listUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, 320));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, 20));

        jLabel6.setText("Cedula");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 320, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 320, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 320, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 320, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 90, 30));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Usuarios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("Valores no disponibles");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoseguridad/fondo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(this.btnEditar.getText().equals("Editar")){
            habilitacionTextos(true);
            this.btnCancelar.setVisible(true);
            this.btnEditar.setText("Actualizar");
        }
        else{ 
            if(ValidarCampos()){
                Usuario paraEditar = new Usuario(this.txtNombre.getText(),this.txtApellido.getText(),this.txtCedula.getText(),this.txtPassword.getText());
                ABM.editarUsuario(paraEditar, seleccionado.getCedula());
                cargarPagina(); 
            }
            else{
                this.lblError.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void listUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listUsuariosValueChanged
        int index= this.listUsuarios.getSelectedIndex();
        seleccionado = this.misusuarios.get(index);
        this.txtNombre.setText(seleccionado.getNombre());
        this.txtApellido.setText(seleccionado.getApellido());
        this.txtCedula.setText(seleccionado.getCedula());
        this.txtPassword.setText(seleccionado.getPass());
    }//GEN-LAST:event_listUsuariosValueChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.txtNombre.setText(seleccionado.getNombre());
        this.txtApellido.setText(seleccionado.getApellido());
        this.txtCedula.setText(seleccionado.getCedula());
        this.txtPassword.setText(seleccionado.getPass());
        this.btnEditar.setText("Editar");
        this.lblError.setVisible(false);
        this.btnCancelar.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionMenu().setVisible(true);
            }
        });
    }
    
    public boolean ValidarCampos(){
     boolean resultado = false;
     boolean sql = Funciones.sqlInyection(this.txtNombre.getText()) && Funciones.sqlInyection(this.txtApellido.getText()) && Funciones.sqlInyection(this.txtCedula.getText()) && Funciones.sqlInyection(this.txtPassword.getText());
     boolean vacio = !this.txtNombre.getText().isEmpty() && !this.txtApellido.getText().isEmpty() && !this.txtCedula.getText().isEmpty() && !this.txtPassword.getText().isEmpty();
     return vacio && sql;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JList<String> listUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    
}
